/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import Delegates.PaymentInterface;
import Entities.Customer;
import Entities.Discount;
import Entities.FixedDiscount;
import Entities.FlexibleDiscount;
import Entities.Invoice;
import Entities.JobStock;
import Entities.Mechanic;
import Entities.VariableDiscount;
import Entities.Vehicle;
import Helpers.ConfigHelper;
import Helpers.PrintHelper;
import Interfaces.TakePaymentFrame;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Daven
 */
public class InvoicePanel extends javax.swing.JPanel {

    Invoice invoice;
    PaymentInterface delegate;
    ConfigHelper configHelper = new ConfigHelper();
    Double VAT = 0.0;
    Double markup = 0.0;
    Double totalCost = 0.0;

    /**
     * Creates new form InvoicePanel
     */
    public InvoicePanel() {
        initComponents();

    }

    public void setup() {
        VAT = configHelper.getVATRate();
        markup = configHelper.getMarkupRate();
    }

    public void setDelegate(PaymentInterface frame) {
        this.delegate = frame;
    }

    public void paid() {
        delegate.paid();
    }

    public void setInvoice(Invoice invoice_) {
        invoice = invoice_;

        Customer customer = invoice.job().customer();
        addressLabel.setText(customer.address());
        postcodeLabel.setText(customer.postcode());
        customerNameLabel.setText(customer.firstName() + " " + customer.lastName());

        Date date = new Date();
        Format formatter = new SimpleDateFormat("dd MMMM yyyy");
        String s = formatter.format(new Date());
        dateLabel.setText(s);

        invoiceNumberLabel.setText("INVOICE NO.: " + invoice.job().ID());

        Vehicle vehicle = invoice.job().vehicle();

        makeTextField.setText("Make: " + vehicle.make());
        modelTextField.setText("Model: " + vehicle.model());
        regTextField.setText("Vehicle Registration No.: " + vehicle.regNo());

        totalCost = 0.0;

        for (JobStock stock : invoice.job().items()) {
            totalCost = totalCost + (stock.cost() * ((100 + markup) / 100) * stock.jobQuantity());
        }

        for (Mechanic mech : invoice.job().mechanics()) {
            totalCost = totalCost + ((mech.hourlyRate() / 60) * mech.minsWorked());
        }

        initialTotalLabel.setText("Total: £" + totalCost);
        VATLabel.setText("VAT: " + VAT + "%");
        totalCost = totalCost * ((100 + VAT) / 100);

        Discount discount = invoice.job().customer().discount();
        Double rate = 0.0;
        if (discount instanceof FixedDiscount) {
            rate = ((FixedDiscount) discount).rate();
            totalCost = ((FixedDiscount) discount).calculateCost(totalCost);
        } else if (discount instanceof FlexibleDiscount) {
            rate = ((FlexibleDiscount) discount).rate(totalCost);
            totalCost = ((FlexibleDiscount) discount).calculateCost(totalCost);
        } else if (discount instanceof VariableDiscount) {
            rate = ((VariableDiscount) discount).rate(totalCost, invoice.job().jobType());
            totalCost = ((VariableDiscount) discount).calculateCost(totalCost, invoice.job().jobType());
        }

        discountLabel.setText("Discount: -" + rate + "%");

        finalTotalLabel.setText("Grand total: £" + String.format("%.2f", totalCost));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        finalTotalLabel = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        postcodeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        invoiceNumberLabel = new javax.swing.JLabel();
        regTextField = new javax.swing.JLabel();
        makeTextField = new javax.swing.JLabel();
        modelTextField = new javax.swing.JLabel();
        initialTotalLabel = new javax.swing.JLabel();
        VATLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        discountLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Invoice");

        finalTotalLabel.setText("Total Amount:");

        customerNameLabel.setText("Customer Name");

        addressLabel.setText("Address");

        postcodeLabel.setText("Postcode");

        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dateLabel.setText("Date");

        invoiceNumberLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        invoiceNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invoiceNumberLabel.setText("INVOICE NO.");

        regTextField.setText("Vehicle Reg. Number:");

        makeTextField.setText("Make:");

        modelTextField.setText("Model:");

        initialTotalLabel.setText("Total:");

        VATLabel.setText("VAT:");

        jButton1.setText("Pay Now");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        discountLabel.setText("Discount:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(invoiceNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerNameLabel)
                            .addComponent(addressLabel)
                            .addComponent(postcodeLabel)
                            .addComponent(regTextField)
                            .addComponent(makeTextField)
                            .addComponent(modelTextField)
                            .addComponent(jLabel1)
                            .addComponent(finalTotalLabel)
                            .addComponent(VATLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(printButton))
                            .addComponent(initialTotalLabel)
                            .addComponent(discountLabel))
                        .addGap(0, 328, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postcodeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invoiceNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(makeTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modelTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(initialTotalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VATLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finalTotalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(saveButton)
                    .addComponent(printButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        new PrintHelper().printJobInvoice(invoice, false);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TakePaymentFrame frame = new TakePaymentFrame();
        frame.setDelegate(this.delegate);
        frame.setAmount(totalCost);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:
        new PrintHelper().printJobInvoice(invoice, true);
    }//GEN-LAST:event_printButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VATLabel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JLabel finalTotalLabel;
    private javax.swing.JLabel initialTotalLabel;
    private javax.swing.JLabel invoiceNumberLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel makeTextField;
    private javax.swing.JLabel modelTextField;
    private javax.swing.JLabel postcodeLabel;
    private javax.swing.JButton printButton;
    private javax.swing.JLabel regTextField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
